#!/bin/bash
# reload configuration of snmpd-poller

pidof=`ps axu | awk '/\/etc\/snmp\/subagent\/snmpd-poller/{print $2}'`
if [ -z $pidof ]; then
  echo "net snmp subagent is not runnung"
  exit 1;
fi

kill -HUP $pidof
