#!/bin/sh
#
# messagebus:   The snmpd subagent 
#
# chkconfig:    345 22 85 
# description:  This is a daemon extend standard snmp functionality with user defined MIB
#
# processname: subagent-shell
# pidfile: /var/run/subagent-shell.pid
#

# Sanity checks.
[ -x /usr/bin/subagent-shell ] || exit 0
[ -f /etc/sysconfig/subagent-shell.options ] && source /etc/sysconfig/subagent-shell.options
RETVAL=0
source /etc/rc.d/init.d/functions

start() {
    echo -n $"Starting snmp subagent shell daemon: "
    [ -z "$OPTIONS" ] && OPTIONS="-d -p /var/run/subagent-shell.pid"
    daemon /usr/bin/subagent-shell $OPTIONS
    RETVAL=$?
    echo
}

stop() {
    echo -n $"Stopping snmp subagent shell daemon: "
    killproc /usr/sbin/subagent-shell
    RETVAL=$?
    echo
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status -p /var/run/subagent-shell.pid subagent-shell
        RETVAL=$?
        ;;
    restart)
        stop
        start
        ;;
    condrestart)
        stop
        start
        ;;
    reload)
        echo "Subagent-shell can't reload its configuration, you have to restart it"
        RETVAL=$?
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|reload}"
        ;;
esac
exit $RETVAL
