#!/bin/sh
#
# messagebus:   The snmpd subagent 
#
# chkconfig:    345 22 85 
# description:  This is a daemon extend standard snmp functionality with user defined MIB
#
# processname: subagent-shell
# pidfile: /var/run/subagent-shell.pid
#

# Sanity checks.
[ -x /usr/bin/subagent-shell ] || exit 0
[ -f /etc/sysconfig/subagent-shell.options ] && source /etc/sysconfig/subagent-shell.options
RETVAL=0
source /etc/init.d/functions

start() {
    echo -n $"Starting snmp subagent shell daemon: "
    [ -z "$OPTIONS" ] && OPTIONS="-d -p /var/run/subagent-shell.pid"
    daemon /usr/bin/subagent-shell $OPTIONS
    RETVAL=$?
    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/subagent-shell
    echo
    return $RETVAL
}

stop() {
    echo -n $"Stopping snmp subagent shell daemon: "
    killproc /usr/sbin/subagent-shell
    RETVAL=$?
    [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/subagent-shell
    echo
    return $RETVAL
}

restart(){
	stop
	start
}

condrestart(){
    [ -e /var/lock/subsys/subagent-shell ] && restart
    return 0
}


case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status -p /var/run/subagent-shell.pid subagent-shell
        RETVAL=$?
        ;;
    restart)
        restart
        ;;
    condrestart)
        condrestart
        ;;
    reload)
        echo "Subagent-shell does not support configuration reload you have to restart it"
        RETVAL=$?
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart}"
        ;;
esac
exit $RETVAL
